# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPU-Emulator-Z80
version:      1.0
version_from: lib/CPU/Emulator/Z80.pm
installdirs:  site
requires:
    CPU::Emulator::Memory::Banked: 1.1
    Scalar::Util:                  0
    Tie::Hash::Vivify:             0.01
    YAML::Tiny:                    1.25

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
